name: Build and Push Docker Images

on:
  push:
    branches:
      - master  # Trigger the action only on pushes to the main branch
  pull_request:
    branches:
      - master  # Trigger on pull request events

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Node.js for frontend and backend
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Specify the Node.js version
        
    # Install dependencies and run unit tests for frontend
    - name: Install and test frontend
      working-directory: .
      run: |
        npm install
        npm test

    # Set up Docker Buildx (for building multi-platform images)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log into DockerHub (or GitHub Container Registry)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and push frontend Docker image
    - name: Build and push frontend image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

